name: Test & Test Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - run: yarn install --dev
      - run: yarn test
      - run: yarn build
